# config.yaml
# var names in ALL CAPS
# booleans are True or False
# most things should be strings
OFFLINE: False
REFRESH: False
SITENAME: "a lynn blog"
AVATAR: "http://www.gravatar.com/avatar/b1cde28ce033c8cd6f4be4059efbe00b.png?size=160"
URL: "http://lynncyrin.me"
DESC: "Queer, Feminist, Programmer"
